### ISSUE TITLE
pypi packages

### ISSUE THREAD

**Issue by bionicles** [jxbz/madam#1]
thank you for the interesting paper and for the jax implementation

would it be possible to publish an official pip package so we could do `pip install jax-madam` and `from jax_madam import madam` etc?

**Comment by jxbz** [comment]
Hey @bionicles, thanks for the interest! I still regard this as an active research project so I'm a little hesitant to create an official package just yet. As a compromise, I've isolated the Jax optimiser into this file: https://github.com/jxbz/madam/blob/master/jax/madam.py
